baseURL: 'https://armin-ashrafi.github.io/'
languageCode: 'en-us'
title: "Armin's Blog"
theme: 'hugo-PaperMod'
sectionPagesMenue: 'main'

menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: Google
      name: Google.com
      url: https://google.com
      weight: 30