baseURL: 'https://armin-ashrafi.github.io/'
languageCode: 'en-us'
title: "Armin's Blog"
theme: 'hugo-PaperMod'
sectionPagesMenue: 'main'

menu:
  main:
    - identifier: Curriculum Vitae
      name: CV
      url: /documents/cv.pdf
      weight: 10
    - identifier: Machine Learning Mastery
      name: Machine Learning
      url: https://machinelearningmastery.com/blog/
      weight: 20
    - identifier: HuggingFace
      name: HuggingFace
      url: https://huggingface.co
      weight: 30